name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential
          git clone https://github.com/google/googletest.git ../googletest
          mkdir -p ../googletest/build
          pushd ../googletest/build
          cmake .. -DBUILD_GMOCK=OFF
          make
          popd

      - name: Build binary
        run: make GTEST=../googletest
        shell: bash

      - name: Build tests
        run: make test GTEST=../googletest
        shell: bash

      - name: Run tests
        run: ./test
        shell: bash
